'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class account_add
    
    '''<summary>
    '''tb_AccountName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_AccountName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_AccountNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_AccountNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_ContractNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_ContractNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_ReferredBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_ReferredBy As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_FederalTaxpayerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_FederalTaxpayerID As Global.Telerik.Web.UI.RadMaskedTextBox

    '''<summary>
    '''tb_TRUCRSID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_TRUCRSID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_NAICScode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_NAICScode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_USDOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_USDOT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_OtherPermit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_OtherPermit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tb_Address1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Address1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_Telephone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Telephone1 As Global.Telerik.Web.UI.RadMaskedTextBox
    
    '''<summary>
    '''tb_Ext1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Ext1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_Address2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Address2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_Telephone2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Telephone2 As Global.Telerik.Web.UI.RadMaskedTextBox
    
    '''<summary>
    '''tb_Ext2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Ext2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_City control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_City As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_Telephone3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Telephone3 As Global.Telerik.Web.UI.RadMaskedTextBox
    
    '''<summary>
    '''tb_Ext3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Ext3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_State As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_CellPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_CellPhone As Global.Telerik.Web.UI.RadMaskedTextBox
    
    '''<summary>
    '''tb_Zip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Zip As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_Fax1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Fax1 As Global.Telerik.Web.UI.RadMaskedTextBox
    
    '''<summary>
    '''tb_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_Notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_Notes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tb_NotesCF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tb_NotesCF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsert As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''sds_CF_Menu_Console control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_CF_Menu_Console As Global.System.Web.UI.WebControls.SqlDataSource
End Class
