'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class account_details1
    
    '''<summary>
    '''FormView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormView1 As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''tbs_AccountDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbs_AccountDetails As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''rmp_AccountDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmp_AccountDetails As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''rpv_Contacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpv_Contacts As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadGrid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid2 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''sds_rpv_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_rpv_Contact As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''btn_AddContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddContact As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rpv_Notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpv_Notes As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''FormView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormView2 As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''rpv_InternalNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpv_InternalNotes As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''FormView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormView3 As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''rpv_PublicDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpv_PublicDocuments As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''rgd_PublicDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_PublicDocuments As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rpv_TerminalDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpv_TerminalDocuments As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''rgd_TerminalDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_TerminalDocuments As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''sdsfvAccountDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsfvAccountDetails As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_CF_Menu_Console control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_CF_Menu_Console As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsfvAccountDetailsNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsfvAccountDetailsNotes As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsfvAccountDetailsInternalNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsfvAccountDetailsInternalNotes As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_Op_IDClass78BACTReplacementSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_IDClass78BACTReplacementSchedule As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_PublicDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_PublicDocuments As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_Op_PublicDocumentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_PublicDocumentType As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_TerminalDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_TerminalDocuments As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''src_DefaultModules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents src_DefaultModules As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_Op_AccountTerminals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_AccountTerminals As Global.System.Web.UI.WebControls.SqlDataSource
End Class
