'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class accounts_user_del
    
    '''<summary>
    '''LoginName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginName As Global.System.Web.UI.WebControls.LoginName
    
    '''<summary>
    '''LoginStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginStatus As Global.System.Web.UI.WebControls.LoginStatus
    
    '''<summary>
    '''RadPanelBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPanelBar1 As Global.Telerik.Web.UI.RadPanelBar
    
    '''<summary>
    '''FormView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormView1 As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''sds_CF_Menu_Console control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_CF_Menu_Console As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Contact As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''RadFormDecorator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadFormDecorator1 As Global.Telerik.Web.UI.RadFormDecorator
End Class
