'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class bluereport_fleet_display
    
    '''<summary>
    '''FormView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormView1 As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''RadListView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadListView1 As Global.Telerik.Web.UI.RadListView
    
    '''<summary>
    '''rsm_CF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsm_CF As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''sds_ReportVehicles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ReportVehicles As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ReportEnginesDECS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ReportEnginesDECS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
