'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class addCARBrecord
    
    '''<summary>
    '''DateValidationPrompt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateValidationPrompt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SuccessfulPrompt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuccessfulPrompt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''HappenedValidationPrompt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HappenedValidationPrompt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBox_CARB_Happened control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_CARB_Happened As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox_CARB_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_CARB_Date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox_CARB_Issue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_CARB_Issue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox_CARB_Resolution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox_CARB_Resolution As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AddCARBButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddCARBButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DoneButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DoneButton As Global.System.Web.UI.WebControls.Button
End Class
