'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class dmvreport
    
    '''<summary>
    '''FileUploadControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploadControl As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''TestButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ChassisVIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChassisVIN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PopulateFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopulateFields As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ChassisVIN_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChassisVIN_Error As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FromDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ThroughDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThroughDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cv_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cv_Date As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''Make control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Make As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Year As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''YrFirstSold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YrFirstSold As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''VlfClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VlfClass As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TypeVeh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeVeh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TypeLic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeLic As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LicensePlateNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LicensePlateNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BodyType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BodyType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''MP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''MO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TypeVehicleUse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeVehicleUse As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DateIssued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateIssued As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CCAlco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCAlco As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DateFeeReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateFeeReceived As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Pic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pic As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''StickerIssued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StickerIssued As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AmountPaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountPaid As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SubmitRegistration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitRegistration As Global.System.Web.UI.WebControls.Button
End Class
