'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class dmvreport
    
    '''<summary>
    '''RadTabStrip1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''RadMultiPagetab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMultiPagetab As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''DMV_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DMV_Add As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''ChassisVIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChassisVIN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PopulateFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopulateFields As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''YrDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YrDropDown As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ChassisVIN_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChassisVIN_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ChassisVIN_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChassisVIN_Error As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FromDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''FromDate_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FromDate_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ThroughDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThroughDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ThroughDate_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThroughDate_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cv_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cv_Date As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''Make control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Make As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Year As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''YrFirstSold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YrFirstSold As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''VlfClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VlfClass As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TypeVeh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeVeh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TypeLic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeLic As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LicensePlateNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LicensePlateNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LicensePlateNo_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LicensePlateNo_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''BodyType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BodyType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''MP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''MO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TypeVehicleUse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeVehicleUse As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DateIssued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateIssued As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DateIssued_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateIssued_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''CCAlco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCAlco As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DateFeeReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateFeeReceived As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DateFeeReceived_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateFeeReceived_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''Pic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pic As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''StickerIssued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StickerIssued As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''StickerIssued_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StickerIssued_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Name_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Name_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''AmountPaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountPaid As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AmountPaid_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountPaid_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Address_Validator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address_Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''SubmitRegistration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitRegistration As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DMV_Edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DMV_Edit As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RecordsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecordsTable As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''sds_Registration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Registration As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DMV_Record control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DMV_Record As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''FromDate_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FromDate_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ThroughDate_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThroughDate_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Make_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Make_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Year_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Year_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''YrFirstSold_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YrFirstSold_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''VlfClass_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VlfClass_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TypeVeh_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeVeh_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TypeLic_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeLic_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LicensePlateNo_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LicensePlateNo_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BodyType_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BodyType_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MP_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MP_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MO_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MO_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TypeVehicleUse_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeVehicleUse_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateIssued_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateIssued_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CCAlco_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CCAlco_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateFeeReceived_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateFeeReceived_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Pic_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pic_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''StickerIssued_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StickerIssued_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Name_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Name_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AmountPaid_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmountPaid_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Address_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address_View As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UpdateRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateRecord As Global.System.Web.UI.WebControls.Button
End Class
