'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class vehiclesadd1
    
    '''<summary>
    '''lbl_FleetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FleetName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbx_UnitNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_UnitNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tbx_ChassisVIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_ChassisVIN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''VINValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VINValidator As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''ddl_LicensePlateState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_LicensePlateState As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LicensePlateStateValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LicensePlateStateValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tbx_LicensePlateNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_LicensePlateNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''tbx_GrossVehicleWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_GrossVehicleWeight As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LicensePlateNoValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LicensePlateNoValidator As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''tbx_AnnualMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_AnnualMiles As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddl_IDEquipmentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_IDEquipmentType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbx_EstReplacementCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_EstReplacementCost As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbx_AnnualHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_AnnualHours As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddl_IDEquipmentCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_IDEquipmentCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddl_ChassisMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_ChassisMake As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbx_ActualMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_ActualMiles As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddl_IDVehicleStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_IDVehicleStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbx_ChassisModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_ChassisModel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbx_ActualHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_ActualHours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_IDCARBGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_IDCARBGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_BasedOutsideCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_BasedOutsideCA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_GPSEquipped control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_GPSEquipped As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_AllWheelDrive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_AllWheelDrive As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddl_WeightClassBin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_WeightClassBin As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddl_ChassisModelYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_ChassisModelYear As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RequiredFieldValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BasedOutsideCAValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BasedOutsideCAdValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''GPSEquippedValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GPSEquippedValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''AllWheelDriveValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllWheelDriveValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''WeightClassBinValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WeightClassBinValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rdp_PlannedComplianceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_PlannedComplianceDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdp_PlannedRetirementDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_PlannedRetirementDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdp_BackupStatusDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_BackupStatusDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdp_ActualComplianceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_ActualComplianceDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdp_ActualRetirementDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_ActualRetirementDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdp_RetireStatusDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_RetireStatusDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdp_LastOpacityTestDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_LastOpacityTestDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''tbx_Description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_Description As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbx_Notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_Notes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbx_NotesCF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_NotesCF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsert As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hf_IDProfileFleet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_IDProfileFleet As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_fleetsRuleCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_fleetsRuleCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_onRoadRuleCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_onRoadRuleCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_lightRuleCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_lightRuleCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_heavyRuleCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_heavyRuleCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''sds_ddl_Op_EquipType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_EquipType As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_Op_EquipCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_EquipCat As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_Op_VehStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_VehStatus As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_Op_CARBGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_CARBGroup As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_Op_ChassisMake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_ChassisMake As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_Op_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_Year As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sds_ddl_Op_State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_State As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sds_ddl_BasedOutsideCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_BasedOutsideCA As Global.System.Web.UI.WebControls.SqlDataSource
    '''<summary>
    '''sds_ddl_BasedOutsideCA1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_BasedOutsideCA1 As Global.System.Web.UI.WebControls.SqlDataSource
    '''<summary>
    '''sds_ddl_BasedOutsideCA2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_BasedOutsideCA2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sds_ddl_WeightClassBin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_WeightClassBin As Global.System.Web.UI.WebControls.SqlDataSource
End Class
