'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DECs_detached
    
    '''<summary>
    '''rg_DECs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rg_DECs As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''fv_DECSDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fv_DECSDetails As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''btn_AddDECSImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddDECSImage As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rg_DECSImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rg_DECSImages As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''btn_AddDECSFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddDECSFile As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rg_DECsFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rg_DECsFiles As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''sds_CFV_DECs_Grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_CFV_DECs_Grid As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_CFV_DECs_fv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_CFV_DECs_fv As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_DECs_Op_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_DECs_Op_Level As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_DECs_Op_Manufacturer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_DECs_Op_Manufacturer As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ImagesDECs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ImagesDECs As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_FilesDECS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_FilesDECS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
