Imports System.Web.Security
Imports System.Web.Security.Roles
Imports System.Web.Security.Membership
Imports System.Data
Imports System.Data.SqlClient
Imports Telerik.Web.UI
Imports System.Collections.Generic
Public Class DECs_detached
    Inherits BaseWebForm

    Protected Sub Page_PreRender(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.PreRender
        Dim rg_DECs As RadGrid = CType(FindControlIterative(Page, "rg_DECs"), RadGrid)
        If rg_DECs.SelectedIndexes.Count = 0 Then
            rg_DECs.SelectedIndexes.Add(0)
        End If
    End Sub




    Protected Sub sds_CFV_DECs_fv_Updating(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.SqlDataSourceCommandEventArgs) Handles sds_CFV_DECs_fv.Updating
        Dim UserID As String
        Dim MemUser As MembershipUser
        MemUser = Membership.GetUser()
        UserID = MemUser.ProviderUserKey.ToString()

        If MemUser Is Nothing Then
            e.Cancel = True
        Else
            e.Command.Parameters("@IDModifiedUser").Value = UserID.ToString()
            e.Command.Parameters("@ModifiedDate").Value = DateTime.Now
        End If
    End Sub

    Protected Sub btn_AddDECSImage_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btn_AddDECSImage.Click
        Dim IDDEC As HiddenField = CType(fv_DECSDetails.FindControl("hf_IDDECS"), HiddenField)
        Dim IDDECS As String = IDDEC.Value
        Dim sbScript As New StringBuilder()

        sbScript.Append("<script language='javascript'>")
        sbScript.Append("window.open('")
        sbScript.Append("../../../includes/imagemanager/imageupload_DECS.aspx?IDDECS=" & IDDECS)
        sbScript.Append("', 'CustomPopUp',")
        sbScript.Append("'width=800, height=600, menubar=yes, resizable=yes');<")
        sbScript.Append("/script>")

        ' Make use ScriptManager to register the script
        ScriptManager.RegisterStartupScript(Me, Me.[GetType](), "@@@@MyPopUpScript", sbScript.ToString(), False)

    End Sub

    Protected Sub btn_AddDECSFile_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btn_AddDECSFile.Click

        Dim IDDEC As HiddenField = CType(fv_DECSDetails.FindControl("hf_IDDECS"), HiddenField)
        Dim IDDECS As String = IDDEC.Value
        Dim sbScript As New StringBuilder()

        sbScript.Append("<script language='javascript'>")
        sbScript.Append("window.open('")
        sbScript.Append("../../../includes/filemanager/fileupload_DECS.aspx?IDDECS=" & IDDECS)
        sbScript.Append("', 'CustomPopUp',")
        sbScript.Append("'width=800, height=600, menubar=yes, resizable=yes');<")
        sbScript.Append("/script>")

        ' Make use ScriptManager to register the script
        ScriptManager.RegisterStartupScript(Me, Me.[GetType](), "@@@@MyPopUpScript", sbScript.ToString(), False)
    End Sub
    Protected Sub rg_DECSImages_ItemCreated(ByVal sender As Object, ByVal e As GridItemEventArgs) Handles rg_DECSImages.ItemCreated
        If TypeOf e.Item Is GridDataItem Then
            Dim item As GridDataItem = DirectCast(e.Item, GridDataItem)
            Dim deleteBtn As LinkButton = DirectCast(item.FindControl("AutoGeneratedDeleteButton"), LinkButton)
            deleteBtn.Attributes.Add("onclick", "return confirm('Are you sure you want to delete this row or record?')")
        End If
    End Sub


    Protected Sub rg_DECsFiles_ItemCreated(ByVal sender As Object, ByVal e As GridItemEventArgs) Handles rg_DECsFiles.ItemCreated
        If TypeOf e.Item Is GridDataItem Then
            Dim item As GridDataItem = DirectCast(e.Item, GridDataItem)
            Dim deleteBtn As LinkButton = DirectCast(item.FindControl("AutoGeneratedDeleteButton"), LinkButton)
            deleteBtn.Attributes.Add("onclick", "return confirm('Are you sure you want to delete this row or record?')")
        End If
    End Sub

    Protected Sub rg_DECSImages_PreRender(ByVal sender As Object, ByVal e As System.EventArgs) Handles rg_DECSImages.PreRender
        rg_DECSImages.MasterTableView.Rebind()
    End Sub

    Protected Sub rg_DECsFiles_PreRender(ByVal sender As Object, ByVal e As System.EventArgs) Handles rg_DECsFiles.PreRender
        rg_DECsFiles.MasterTableView.Rebind()
    End Sub

    Protected Sub sds_CFV_DECs_Grid_Selected(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.SqlDataSourceStatusEventArgs) Handles sds_CFV_DECs_Grid.Selected

        If e.AffectedRows < 1 Then

            btn_AddDECSImage.Visible = False
            btn_AddDECSFile.Visible = False

        End If

    End Sub

    ' MG 12/14/2011 - there were problems finding hf_IDDECS control on page (different tab maybe?), so I use this function to find it instead
    Public Shared Function FindControlIterative(ByVal myRoot As Control, ByVal myIDOfControlToFind As String) As Control
        Dim myRootControl As Control = New Control
        myRootControl = myRoot
        Dim setOfChildControls As LinkedList(Of Control) = New LinkedList(Of Control)

        Do While (myRootControl IsNot Nothing)
            If myRootControl.ID = myIDOfControlToFind Then
                Return myRootControl
            End If
            For Each childControl As Control In myRootControl.Controls
                If childControl.ID = myIDOfControlToFind Then
                    Return childControl
                End If
                If childControl.HasControls() Then
                    setOfChildControls.AddLast(childControl)
                End If
            Next
            myRootControl = setOfChildControls.First.Value
            setOfChildControls.Remove(myRootControl)
        Loop
        Return Nothing

    End Function

End Class
