'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default3
    
    '''<summary>
    '''lbl_Account control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Account As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_User As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadGrid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid2 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGrid3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid3 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGrid4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid4 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGrid5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid5 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''CustomModulesPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomModulesPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''rgd_ComplianceCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_ComplianceCertification As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rgd_FleetSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_FleetSummary As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rgd_OpacityTests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_OpacityTests As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rgd_EngineModelYearReplacementSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_EngineModelYearReplacementSchedule As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rgd_STBPhaseInOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_STBPhaseInOption As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rgd_LowMileageConstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_LowMileageConstruction As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rgd_NOxExempt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_NOxExempt As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rgd_TerminalComplianceCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_TerminalComplianceCertification As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rgd_TerminalFleetSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_TerminalFleetSummary As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rgd_TerminalOpacityTests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_TerminalOpacityTests As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''sds_Profile_Terminal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Profile_Terminal As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_Profile_Fleet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Profile_Fleet As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_Vehicles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Vehicles As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_Users control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Users As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ComplianceCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ComplianceCertification As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_FleetSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_FleetSummary As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_OpacityTests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_OpacityTests As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_EngineModelYearReplacementSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_EngineModelYearReplacementSchedule As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_STBPhaseInOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_STBPhaseInOption As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_LowMileageConstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_LowMileageConstruction As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_NOxExempt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_NOxExempt As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_TerminalComplianceCertification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_TerminalComplianceCertification As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_TerminalFleetSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_TerminalFleetSummary As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_TerminalOpacityTests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_TerminalOpacityTests As Global.System.Web.UI.WebControls.SqlDataSource
End Class
