'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class bluereport_fleet_CARB
    
    '''<summary>
    '''ddl_CARBGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_CARBGroup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cv_ddl_CARBGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cv_ddl_CARBGroup As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''btn_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Report As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''sds_ddl_Account control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Account As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_ddl_Op_CARBGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_ddl_Op_CARBGroup As Global.System.Web.UI.WebControls.SqlDataSource
End Class
