CREATE TABLE [dbo].[CF_Import] (
    [Account]               VARCHAR (250)   NULL,
    [Terminal]              VARCHAR (250)   NULL,
    [Fleet]                 VARCHAR (250)   NULL,
    [UnitNo]                VARCHAR (250)   NULL,
    [LicensePlateNo]        VARCHAR (250)   NULL,
    [ChassisVIN]            VARCHAR (250)   NULL,
    [EquipmentType]         VARCHAR (250)   NULL,
    [EquipmentCategory]     VARCHAR (250)   NULL,
    [VehicleStatus]         VARCHAR (250)   NULL,
    [CARBGroup]             VARCHAR (250)   NULL,
    [ChassisMake]           VARCHAR (250)   NULL,
    [ChassisModelYear]      VARCHAR (250)   NULL,
    [AnnualMiles]           VARCHAR (250)   NULL,
    [AnnualHours]           VARCHAR (250)   NULL,
    [ActualMiles]           VARCHAR (250)   NULL,
    [ActualHours]           VARCHAR (250)   NULL,
    [GrossVehicleWeight]    VARCHAR (250)   NULL,
    [PlannedComplianceDate] DATETIME        NULL,
    [ActualComplianceDate]  DATETIME        NULL,
    [BackupStatusDate]      DATETIME        NULL,
    [RetireStatusDate]      DATETIME        NULL,
    [EstReplacementCost]    MONEY           NULL,
    [PlannedRetirementDate] DATETIME        NULL,
    [ActualRetirementDate]  DATETIME        NULL,
    [EngineManufacturer]    VARCHAR (250)   NULL,
    [EngineModel]           VARCHAR (250)   NULL,
    [EngineStatus]          VARCHAR (250)   NULL,
    [EngineFuelType]        VARCHAR (250)   NULL,
    [ModelYear]             VARCHAR (250)   NULL,
    [SerialNum]             VARCHAR (250)   NULL,
    [FamilyName]            VARCHAR (250)   NULL,
    [SeriesModelNo]         VARCHAR (250)   NULL,
    [Horsepower]            VARCHAR (250)   NULL,
    [Displacement]          DECIMAL (18, 5) NULL,
    [EstRetrofitCost]       MONEY           NULL,
    [DECSName]              VARCHAR (250)   NULL,
    [SerialNo]              VARCHAR (250)   NULL,
    [DECSManufacturer]      VARCHAR (250)   NULL,
    [DECSLevel]             VARCHAR (250)   NULL,
    [DECSModelNo]           VARCHAR (250)   NULL,
    [DECSInstallationDate]  DATETIME        NULL
);

