CREATE TABLE [dbo].[CF_Profile_Account] (
    [IDProfileAccount]                 INT              IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [IDModifiedUser]                   UNIQUEIDENTIFIER NULL,
    [Test]                             INT              NULL,
    [EnterDate]                        DATETIME         CONSTRAINT [DF_CF_Profile_Account_EnterDate] DEFAULT (getdate()) NULL,
    [ModifiedDate]                     DATETIME         NULL,
    [IDAccountParent]                  INT              NULL,
    [IDSalesRep]                       INT              NULL,
    [IDCSR]                            INT              NULL,
    [IDPrimaryContact]                 INT              NULL,
    [IsCorpHQ]                         VARCHAR (50)     NULL,
    [AccountName]                      VARCHAR (50)     NULL,
    [AccountNum]                       VARCHAR (50)     NULL,
    [ContractNum]                      VARCHAR (50)     NULL,
    [ReferredBy]                       VARCHAR (50)     NULL,
    [IDClass78BACTReplacementSchedule] INT              CONSTRAINT [DF_CF_Profile_Account_IDClass78BACTReplacementSchedule] DEFAULT ((0)) NULL,
    [PayType]                          VARCHAR (50)     NULL,
    [Discount]                         INT              NULL,
    [DiscountUntilDate]                DATETIME         NULL,
    [Region]                           VARCHAR (50)     NULL,
    [Address1]                         VARCHAR (50)     NULL,
    [Address2]                         VARCHAR (50)     NULL,
    [City]                             VARCHAR (50)     NULL,
    [State]                            VARCHAR (50)     NULL,
    [County]                           VARCHAR (50)     NULL,
    [Country]                          VARCHAR (50)     NULL,
    [Zip]                              VARCHAR (9)      NULL,
    [MailMergeCode]                    VARCHAR (50)     NULL,
    [Telephone1]                       VARCHAR (10)     NULL,
    [Ext1]                             VARCHAR (10)     NULL,
    [Telephone2]                       VARCHAR (10)     NULL,
    [Ext2]                             VARCHAR (10)     NULL,
    [Telephone3]                       VARCHAR (10)     NULL,
    [Ext3]                             VARCHAR (10)     NULL,
    [Fax1]                             VARCHAR (10)     NULL,
    [Fax2]                             VARCHAR (10)     NULL,
    [Email]                            VARCHAR (100)    NULL,
    [WebSite]                          VARCHAR (100)    NULL,
    [Notes]                            NVARCHAR (MAX)   NULL,
    [NotesCF]                          NVARCHAR (MAX)   NULL,
    [PSIPNotificationEmail]            CHAR (1)         CONSTRAINT [DF_CF_Profile_Account_PSIPNotificationEmail] DEFAULT ('N') NULL,
    [PSIPMonth]                        VARCHAR (9)      CONSTRAINT [DF_CF_Profile_Account_PSIPMonth] DEFAULT ('None') NULL,
    [IMAPUsername]                     VARCHAR (64)     NULL,
    [IMAPPassword]                     VARCHAR (64)     NULL,
    [IMAPDraftsFolder]                 VARCHAR (64)     NULL,
    CONSTRAINT [PK_CF_Profile_Account] PRIMARY KEY CLUSTERED ([IDProfileAccount] ASC)
);

