CREATE TABLE [dbo].[CF_Profile_Contact] (
    [IDProfileContact]    INT              IDENTITY (1, 1) NOT NULL,
    [UserID]              UNIQUEIDENTIFIER NOT NULL,
    [IDProfileAccount]    INT              NULL,
    [IDClientAccessLevel] INT              NULL,
    [UserRole]            VARCHAR (50)     NULL,
    [IDModifiedUser]      UNIQUEIDENTIFIER NULL,
    [EnterDate]           DATETIME         CONSTRAINT [DF_CF_Profile_Contact_EnterDate] DEFAULT (getdate()) NULL,
    [ModifiedDate]        DATETIME         NULL,
    [IDPrefix]            INT              NULL,
    [IDPostfix]           INT              NULL,
    [IDTitle]             INT              CONSTRAINT [DF_CF_Profile_Contact_IDTitle] DEFAULT ((0)) NULL,
    [LastName]            VARCHAR (50)     NULL,
    [FirstName]           VARCHAR (50)     NULL,
    [MI]                  VARCHAR (2)      NULL,
    [Title]               VARCHAR (50)     NULL,
    [Address1]            VARCHAR (50)     NULL,
    [Address2]            VARCHAR (50)     NULL,
    [City]                VARCHAR (50)     NULL,
    [State]               VARCHAR (50)     NULL,
    [County]              VARCHAR (50)     NULL,
    [Country]             VARCHAR (50)     NULL,
    [Zip]                 VARCHAR (9)      NULL,
    [MailMergeCode]       VARCHAR (50)     NULL,
    [Telephone1]          VARCHAR (10)     NULL,
    [Ext1]                VARCHAR (10)     NULL,
    [Telephone2]          VARCHAR (10)     NULL,
    [Ext2]                VARCHAR (10)     NULL,
    [Telephone3]          VARCHAR (10)     NULL,
    [Ext3]                VARCHAR (10)     NULL,
    [CellPhone]           VARCHAR (10)     NULL,
    [Fax1]                VARCHAR (10)     NULL,
    [Fax2]                VARCHAR (10)     NULL,
    [EMailMergeCode]      VARCHAR (50)     NULL,
    [WebSite]             VARCHAR (100)    NULL,
    [Notes]               VARCHAR (MAX)    NULL,
    [NotesCF]             VARCHAR (MAX)    NULL,
    [IMAPUsername]        VARCHAR (64)     NULL,
    [IMAPPassword]        VARCHAR (64)     NULL,
    [IMAPDraftsFolder]    VARCHAR (64)     NULL,
    CONSTRAINT [PK_CF_Profile_Contact] PRIMARY KEY CLUSTERED ([UserID] ASC)
);

