CREATE TABLE [dbo].[CF_Profile_Terminal] (
    [IDProfileTerminal] INT              IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [IDModifiedUser]    UNIQUEIDENTIFIER NULL,
    [EnterDate]         DATETIME         CONSTRAINT [DF_CF_Profile_Terminal_EnterDate] DEFAULT (getdate()) NULL,
    [ModifiedDate]      DATETIME         NULL,
    [IDProfileAccount]  INT              NULL,
    [IDPrimaryContact]  INT              NULL,
    [TerminalName]      VARCHAR (50)     NULL,
    [Address1]          VARCHAR (50)     NULL,
    [Address2]          VARCHAR (50)     NULL,
    [City]              VARCHAR (50)     NULL,
    [State]             VARCHAR (50)     NULL,
    [County]            VARCHAR (50)     NULL,
    [Country]           VARCHAR (50)     NULL,
    [Zip]               VARCHAR (9)      NULL,
    [Telephone1]        VARCHAR (10)     NULL,
    [Ext1]              VARCHAR (10)     NULL,
    [Telephone2]        VARCHAR (10)     NULL,
    [Ext2]              VARCHAR (10)     NULL,
    [Telephone3]        VARCHAR (10)     NULL,
    [Ext3]              VARCHAR (10)     NULL,
    [Fax1]              VARCHAR (10)     NULL,
    [Fax2]              VARCHAR (10)     NULL,
    [Email]             VARCHAR (100)    NULL,
    [WebSite]           VARCHAR (100)    NULL,
    [Notes]             VARCHAR (MAX)    NULL,
    [NotesCF]           VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_CF_Profile_Terminal] PRIMARY KEY CLUSTERED ([IDProfileTerminal] ASC),
    CONSTRAINT [FK_CF_Profile_Terminal_CF_Profile_Account] FOREIGN KEY ([IDProfileAccount]) REFERENCES [dbo].[CF_Profile_Account] ([IDProfileAccount]) ON DELETE CASCADE
);

