CREATE TABLE [dbo].[CF_Profile_Fleet] (
    [IDProfileFleet]    INT              IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [IDModifiedUser]    UNIQUEIDENTIFIER NULL,
    [EnterDate]         DATETIME         CONSTRAINT [DF_CF_Profile_Fleet_EnterDate] DEFAULT (getdate()) NULL,
    [ModifiedDate]      DATETIME         NULL,
    [IDProfileTerminal] INT              NULL,
    [IDPrimaryContact]  INT              NULL,
    [IDRuleCode]        INT              CONSTRAINT [DF_CF_Profile_Fleet_IDRuleCode] DEFAULT ((0)) NULL,
    [FleetName]         VARCHAR (50)     NULL,
    [Address1]          VARCHAR (50)     NULL,
    [Address2]          VARCHAR (50)     NULL,
    [City]              VARCHAR (50)     NULL,
    [State]             VARCHAR (50)     NULL,
    [County]            VARCHAR (50)     NULL,
    [Country]           VARCHAR (50)     NULL,
    [Zip]               VARCHAR (9)      NULL,
    [Telephone1]        VARCHAR (10)     NULL,
    [Ext1]              VARCHAR (10)     NULL,
    [Telephone2]        VARCHAR (10)     NULL,
    [Ext2]              VARCHAR (10)     NULL,
    [Telephone3]        VARCHAR (10)     NULL,
    [Ext3]              VARCHAR (10)     NULL,
    [Fax1]              VARCHAR (10)     NULL,
    [Fax2]              VARCHAR (10)     NULL,
    [Email]             VARCHAR (100)    NULL,
    [WebSite]           VARCHAR (100)    NULL,
    [Notes]             VARCHAR (MAX)    NULL,
    [NotesCF]           VARCHAR (MAX)    NULL,
    CONSTRAINT [PK_CF_Profile_Fleet] PRIMARY KEY CLUSTERED ([IDProfileFleet] ASC),
    CONSTRAINT [FK_CF_Profile_Fleet_CF_Profile_Terminal] FOREIGN KEY ([IDProfileTerminal]) REFERENCES [dbo].[CF_Profile_Terminal] ([IDProfileTerminal]) ON DELETE CASCADE
);

