CREATE TABLE [dbo].[Test] (
    [IDVehicles]            INT              IDENTITY (1, 1) NOT NULL,
    [IDVehiclesHH]          NCHAR (10)       NULL,
    [IDModifiedUser]        UNIQUEIDENTIFIER NULL,
    [EnterDate]             DATETIME         NULL,
    [ModifiedDate]          DATETIME         NULL,
    [IDProfileFleet]        INT              NULL,
    [IDEquipmentType]       INT              NULL,
    [IDEquipmentCategory]   INT              NULL,
    [IDVehicleStatus]       INT              NULL,
    [IDCARBGroup]           INT              NULL,
    [LicensePlateNo]        VARCHAR (50)     NOT NULL,
    [ChassisVIN]            VARCHAR (50)     NOT NULL,
    [IDChassisMake]         INT              NULL,
    [IDChassisModelYear]    INT              NULL,
    [IDRuleCode]            INT              NULL,
    [UnitNo]                VARCHAR (50)     NULL,
    [Description]           VARCHAR (MAX)    NULL,
    [AnnualMiles]           VARCHAR (50)     NULL,
    [AnnualHours]           VARCHAR (50)     NULL,
    [ActualMiles]           VARCHAR (50)     NULL,
    [ActualHours]           VARCHAR (50)     NULL,
    [GrossVehicleWeight]    VARCHAR (50)     NULL,
    [PlannedComplianceDate] DATETIME         NULL,
    [ActualComplianceDate]  DATETIME         NULL,
    [BackupStatusDate]      DATETIME         NULL,
    [RetireStatusDate]      DATETIME         NULL,
    [Notes]                 VARCHAR (MAX)    NULL,
    [NotesCF]               VARCHAR (MAX)    NULL,
    [EstReplacementCost]    MONEY            NULL,
    [PlannedRetirementDate] DATETIME         NULL,
    [ActualRetirementDate]  DATETIME         NULL
);

