'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class dropdown_list
    
    '''<summary>
    '''ddl_OptionNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_OptionNames As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rgd_Optionn_Details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_Optionn_Details As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''sds_Option_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Option_List As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_Option_List_rgd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Option_List_rgd As Global.System.Web.UI.WebControls.SqlDataSource
End Class
