'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UploadManager
    
    '''<summary>
    '''LoginName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginName As Global.System.Web.UI.WebControls.LoginName
    
    '''<summary>
    '''LoginStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginStatus As Global.System.Web.UI.WebControls.LoginStatus
    
    '''<summary>
    '''pnlImageHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImageHeading As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlFileHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFileHeading As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCaption As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDocType As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlDocType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDocType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNotes As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DropZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropZone As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Footer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Footer1 As Global.cleanfleets_fms.Footer
    
    '''<summary>
    '''hfType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_IDVehicles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_IDVehicles As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_IDEngines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_IDEngines As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_IDDECS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_IDDECS As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_IDProfileAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_IDProfileAccount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_IDProfileTerminal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_IDProfileTerminal As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hf_IDProfileFleet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf_IDProfileFleet As Global.System.Web.UI.WebControls.HiddenField
End Class
