'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class terminaldetails
    
    '''<summary>
    '''btn_TerminalList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_TerminalList As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''FormView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormView1 As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''tbs_TerminalDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbs_TerminalDetails As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''rmp_AccountDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmp_AccountDetails As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''rpv_TerminalDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpv_TerminalDocuments As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''rgd_TerminalDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgd_TerminalDocuments As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''sds_Profile_Account control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_Profile_Account As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_cfv_Profile_Terminal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_cfv_Profile_Terminal As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sds_TerminalDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_TerminalDocuments As Global.System.Web.UI.WebControls.SqlDataSource
End Class
